"""
main.py — FastAPI application entry point for the Dhaniti backend.

Run (from the backend/ directory):

    uvicorn app.main:app --host 0.0.0.0 --port 5000

Interactive API docs (auto-generated by FastAPI):
    http://localhost:5000/docs      (Swagger UI)
    http://localhost:5000/redoc     (ReDoc)

Served:
  * /api/...        — REST API (see README / docs)
  * /auth/...       — OAuth 2.0 browser redirects (Google, GitHub)
  * /               — the built React app from backend/static/ (SPA fallback)
"""

from __future__ import annotations

import logging
from pathlib import Path

from fastapi import FastAPI, HTTPException, Request
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

from . import config
from .database import init_app_database
from .routes import analytics, auth, crud, oauth

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
logger = logging.getLogger("dhaniti")

# --------------------------------------------------------------------------- #
# App
# --------------------------------------------------------------------------- #
app = FastAPI(
    title=config.API_TITLE,
    version=config.API_VERSION,
    description=(
        "Authentication (email/password, OTP, OAuth), CRUD and analytics API "
        "for the Dhaniti Education Loan Dashboard."
    ),
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=config.CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
    allow_headers=["Authorization", "Content-Type"],
)

# --------------------------------------------------------------------------- #
# Consistent error shape: {"error": "...", "details": [...]}
# --------------------------------------------------------------------------- #
@app.exception_handler(HTTPException)
async def http_exception_handler(request: Request, exc: HTTPException):
    headers = getattr(exc, "headers", None)
    return JSONResponse(
        status_code=exc.status_code,
        content={"error": str(exc.detail), "details": []},
        headers=headers,
    )


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request: Request, exc: RequestValidationError):
    details = []
    for err in exc.errors():
        loc = ".".join(str(part) for part in err.get("loc", []) if part != "body")
        details.append(f"{loc or 'body'}: {err.get('msg', 'invalid value')}")
    return JSONResponse(
        status_code=422,
        content={"error": "Validation failed. Please check the highlighted fields.", "details": details},
    )


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception):
    # Never leak stack traces / internals to the client.
    logger.exception("Unhandled server error on %s %s", request.method, request.url.path)
    return JSONResponse(
        status_code=500,
        content={"error": "Something went wrong on our side. Please try again.", "details": []},
    )


# --------------------------------------------------------------------------- #
# Routers
# --------------------------------------------------------------------------- #
app.include_router(auth.router)
app.include_router(oauth.router)
app.include_router(crud.router)
app.include_router(analytics.router)


# --------------------------------------------------------------------------- #
# Legacy aliases (the original Flask API paths keep working)
# --------------------------------------------------------------------------- #
from pydantic import BaseModel, Field  # noqa: E402
from fastapi import Depends, Response  # noqa: E402

from .routes.auth import LoginRequest, login as _login  # noqa: E402
from .security.authentication import get_current_user  # noqa: E402


class LegacyLoginRequest(BaseModel):
    username: str = Field(min_length=1, max_length=254)
    password: str = Field(min_length=1, max_length=128)


@app.post("/api/login", tags=["Legacy compat"])
def legacy_login(payload: LegacyLoginRequest, request: Request):
    """Old Flask endpoint — accepts username (= email or local part)."""
    converted = LoginRequest(email=payload.username, password=payload.password)
    return _login(converted, request, Response())


@app.get("/api/whoami", tags=["Legacy compat"])
def legacy_whoami(user: dict = Depends(get_current_user)):
    """Old Flask endpoint — returns the current user."""
    return {
        "username": user["email"],
        "name": user["name"],
        "role": user["role"],
    }


# --------------------------------------------------------------------------- #
# Health / root
# --------------------------------------------------------------------------- #
@app.get("/api/health", tags=["Health"])
def health():
    return {"status": "healthy", "app": config.APP_NAME, "version": config.API_VERSION}


# --------------------------------------------------------------------------- #
# Static frontend (built React app) with SPA fallback
# --------------------------------------------------------------------------- #
STATIC_DIR = Path(config.STATIC_DIR)

if (STATIC_DIR / "index.html").exists():
    app.mount("/assets", StaticFiles(directory=STATIC_DIR / "assets"), name="assets")

    @app.get("/", include_in_schema=False)
    async def serve_index():
        return FileResponse(STATIC_DIR / "index.html")

    @app.get("/{full_path:path}", include_in_schema=False)
    async def spa_fallback(full_path: str):
        candidate = STATIC_DIR / full_path
        if full_path and candidate.is_file():
            return FileResponse(candidate)
        # Unknown non-API routes → let the React router handle them (SPA).
        if not full_path.startswith(("api/", "auth/", "docs", "redoc", "openapi.json")):
            return FileResponse(STATIC_DIR / "index.html")
        return JSONResponse(status_code=404, content={"error": "Not found", "details": []})
else:
    @app.get("/", include_in_schema=False)
    async def root():
        return {
            "application": config.APP_NAME,
            "status": "online",
            "message": "Frontend build not found in backend/static/. Run `npm run build` in frontend/ to serve the dashboard.",
            "docs": "/docs",
        }


# --------------------------------------------------------------------------- #
# Startup / shutdown
# --------------------------------------------------------------------------- #
@app.on_event("startup")
async def on_startup():
    init_app_database()
    # Housekeeping: remove long-expired OTP + auth codes.
    try:
        from .services import otp_service
        from .routes.oauth import purge_auth_codes

        otp_service.purge_expired()
        purge_auth_codes()
    except Exception as exc:  # noqa: BLE001
        logger.warning("Startup housekeeping failed: %s", exc)
    if not config.SMTP_CONFIGURED:
        logger.warning(
            "SMTP is not configured — outgoing emails (OTP codes) are written to %s",
            config.EMAIL_OUTBOX_DIR,
        )
    if not (config.GOOGLE_CLIENT_ID and config.GOOGLE_CLIENT_SECRET):
        logger.warning("Google OAuth is not configured (GOOGLE_CLIENT_ID/SECRET missing).")
    if not (config.GITHUB_CLIENT_ID and config.GITHUB_CLIENT_SECRET):
        logger.warning("GitHub OAuth is not configured (GITHUB_CLIENT_ID/SECRET missing).")
